variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "-Dmaven.test.skip=true -s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile deploy
  artifacts:
    paths:
      - target/*.jar
